const { Blockchain } = require('./server/blockchain');

const ledger = new Blockchain();

const departments = [
  {
    name: "Cardiology",
    doctors: [
      { name: "Dr. Rajesh Varma", designation: "Senior Consultant Cardiologist", qualifications: "MD, DM (Cardiology)" },
      { name: "Dr. Sunita Rao", designation: "Associate Consultant", qualifications: "MBBS, DNB (Cardiology)" }
    ]
  },
  {
    name: "Neurology & Neurosurgery",
    doctors: [
      { name: "Dr. Arvind Swaminathan", designation: "Head of Department & Chief Neurosurgeon", qualifications: "MCh (Neurosurgery)" },
      { name: "Dr. Preeti Nair", designation: "Consultant Neurologist", qualifications: "DM (Neurology)" }
    ]
  },
  {
    name: "Orthopaedics & Joint Replacement",
    doctors: [
      { name: "Dr. Vikramaditya Rathore", designation: "Senior Joint Replacement Surgeon", qualifications: "MS (Ortho), Fellowship in Joint Replacement" },
      { name: "Dr. Neha Kulkarni", designation: "Consultant Orthopedic Surgeon", qualifications: "D.Ortho, DNB" }
    ]
  },
  {
    name: "Pediatrics & Neonatology",
    doctors: [
      { name: "Dr. Amit Mehra", designation: "Lead Pediatrician", qualifications: "MD (Pediatrics), FIAP" },
      { name: "Dr. Shalini Deshmukh", designation: "Consultant Neonatologist", qualifications: "MBBS, DCH" }
    ]
  },
  {
    name: "Obstetrics & Gynecology",
    doctors: [
      { name: "Dr. Ananya Sen", designation: "Senior Obstetrician & Gynecologist", qualifications: "MS (OB-GYN), DGO" },
      { name: "Dr. Ritu Bhargava", designation: "Consultant & Laparoscopic Surgeon", qualifications: "MD (OB-GYN)" }
    ]
  },
  {
    name: "General & Laparoscopic Surgery",
    doctors: [
      { name: "Dr. Harish Chandra", designation: "Chief Laparoscopic Surgeon", qualifications: "MS (Gen Surgery), FMAS" },
      { name: "Dr. Pooja Joshi", designation: "General Surgeon", qualifications: "DNB (Surgery)" }
    ]
  },
  {
    name: "Internal Medicine",
    doctors: [
      { name: "Dr. Sanjay Nambiar", designation: "Senior Consultant Physician", qualifications: "MD (General Medicine)" },
      { name: "Dr. Kavita Hegde", designation: "Consultant Physician", qualifications: "MBBS, DNB (Medicine)" }
    ]
  },
  {
    name: "Oncology",
    doctors: [
      { name: "Dr. Siddharth Menon", designation: "Senior Medical Oncologist", qualifications: "DM (Medical Oncology)" },
      { name: "Dr. Maya Pillai", designation: "Consultant Onco-Surgeon", qualifications: "MCh (Surgical Oncology)" }
    ]
  },
  {
    name: "Dermatology & Cosmetology",
    doctors: [
      { name: "Dr. Tanya Kapoor", designation: "Lead Dermatologist", qualifications: "MD (Dermatology, Venereology & Leprosy)" },
      { name: "Dr. Rohan Chawla", designation: "Cosmetic Dermatologist", qualifications: "DVD, FAM" }
    ]
  },
  {
    name: "Radiology & Diagnostics",
    doctors: [
      { name: "Dr. Deepa Natarajan", designation: "Chief Radiologist", qualifications: "MD (Radio-Diagnosis)" },
      { name: "Dr. Kunal Singhania", designation: "Consultant Radiologist", qualifications: "DMRD, DNB" }
    ]
  },
  {
    name: "Emergency & Critical Care",
    doctors: [
      { name: "Dr. Manish Tandon", designation: "Head of Emergency Care", qualifications: "MD (Emergency Medicine)" },
      { name: "Dr. Sneha Patil", designation: "Critical Care Specialist", qualifications: "MEM (Emergency Medicine)" }
    ]
  }
];

const sampleRecords = {
  "Cardiology": [
    { patientId: "P-1001", author: "Dr. Rajesh Varma", data: { diagnosis: "Acute Myocardial Infarction (STEMI)", notes: "Patient presented with crushing chest pain, diaphoresis. ECG showed ST elevation in leads II, III, aVF. Troponin T elevated at 2.4 ng/mL. Emergency PCI performed with stent placement in RCA. Patient stabilized post-procedure.", department: "Cardiology", vitals: { bp: "160/95", hr: 112, spo2: "94%" } } },
    { patientId: "P-1002", author: "Dr. Sunita Rao", data: { diagnosis: "Chronic Heart Failure (NYHA Class III)", notes: "Echocardiography shows EF 35%, LV dilation. BNP elevated at 890 pg/mL. Started on ACE inhibitor, beta-blocker, and diuretic therapy. Patient counseled on salt restriction and daily weight monitoring.", department: "Cardiology", vitals: { bp: "130/85", hr: 88, spo2: "92%" } } },
    { patientId: "P-1003", author: "Dr. Rajesh Varma", data: { diagnosis: "Atrial Fibrillation with Rapid Ventricular Response", notes: "ECG confirmed AFib with HR 142 bpm. CHA2DS2-VASc score: 3. Started on anticoagulation with Apixaban. Rate control with Metoprolol. Echo shows mild LA enlargement.", department: "Cardiology", vitals: { bp: "125/78", hr: 142, spo2: "96%" } } },
    { patientId: "P-1004", author: "Dr. Sunita Rao", data: { diagnosis: "Hypertensive Emergency", notes: "BP recorded at 220/120 mmHg on arrival. End-organ damage noted: acute kidney injury (Creat 2.8), retinopathy grade III. Admitted to ICU, IV Labetalol infusion initiated. BP target: reduce by 25% in first hour.", department: "Cardiology", vitals: { bp: "220/120", hr: 105, spo2: "93%" } } },
    { patientId: "P-1005", author: "Dr. Rajesh Varma", data: { diagnosis: "Stable Angina Pectoris", notes: "Chest pain on exertion, relieved by rest. Stress test positive at 7 METs. Coronary angiography revealed 70% LAD stenosis. Optimal medical therapy initiated. Patient scheduled for follow-up in 2 weeks.", department: "Cardiology", vitals: { bp: "138/82", hr: 76, spo2: "97%" } } },
    { patientId: "P-1006", author: "Dr. Sunita Rao", data: { diagnosis: "Deep Vein Thrombosis - Left Lower Extremity", notes: "Duplex ultrasound confirmed DVT in left popliteal and femoral veins. Patient started on therapeutic anticoagulation with Rivaroxaban. Compression stockings applied. Advised against prolonged immobility.", department: "Cardiology", vitals: { bp: "128/80", hr: 82, spo2: "96%" } } },
    { patientId: "P-1007", author: "Dr. Rajesh Varma", data: { diagnosis: "Mitral Valve Regurgitation - Severe", notes: "Echocardiography shows severe MR with regurgitant fraction 62%. LV dilated (LVIDd 6.2cm). Patient symptomatic with dyspnea on mild exertion. Referred for mitral valve repair surgery. Heart Team discussion planned.", department: "Cardiology", vitals: { bp: "118/72", hr: 92, spo2: "94%" } } },
    { patientId: "P-1008", author: "Dr. Sunita Rao", data: { diagnosis: "Paroxysmal Supraventricular Tachycardia", notes: "Recurrent episodes of palpitations with sudden onset and termination. ECG during episode: SVT at 180 bpm. Vagal maneuvers terminated episode. Electrophysiology study and ablation planned for next week.", department: "Cardiology", vitals: { bp: "115/70", hr: 72, spo2: "97%" } } },
    { patientId: "P-1009", author: "Dr. Rajesh Varma", data: { diagnosis: "Pericarditis - Acute", notes: "Presented with sharp retrosternal chest pain, worse on inspiration. ECG: diffuse ST elevation with PR depression. CRP elevated at 85 mg/L. Echo: small pericardial effusion. Started on NSAIDs and Colchicine.", department: "Cardiology", vitals: { bp: "122/76", hr: 98, spo2: "96%" } } },
    { patientId: "P-1010", author: "Dr. Sunita Rao", data: { diagnosis: "Cardiomyopathy - Dilated", notes: "Echocardiography: EF 28%, global hypokinesia. Cardiac MRI pending. HIV, thyroid, and alcohol screens negative. Family history notable for sudden cardiac death in father at age 52. Genetic testing recommended.", department: "Cardiology", vitals: { bp: "105/68", hr: 100, spo2: "91%" } } },
    { patientId: "P-1011", author: "Dr. Rajesh Varma", data: { diagnosis: "Post-PCI Follow-up", notes: "3-month follow-up after LAD stent placement. Patient asymptomatic, exercise tolerance improved. Repeat stress test normal. Continue DAPT for 12 months total. Statin therapy maintained. LDL target <70 mg/dL achieved.", department: "Cardiology", vitals: { bp: "125/78", hr: 68, spo2: "98%" } } },
    { patientId: "P-1012", author: "Dr. Sunita Rao", data: { diagnosis: "Syncope - Vasovagal", notes: "Recurrent syncope episodes, typically in warm environments. Tilt-table test positive for vasovagal response at 12 minutes. No cardiac etiology identified. Counseled on adequate hydration, salt intake, and counter-pressure maneuvers.", department: "Cardiology", vitals: { bp: "118/74", hr: 65, spo2: "97%" } } }
  ],
  "Neurology & Neurosurgery": [
    { patientId: "P-1013", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Acute Ischemic Stroke - MCA Territory", notes: "CT head negative for hemorrhage. NIHSS score: 14. Last known well 3 hours ago. Patient meets criteria for IV thrombolysis. Alteplase administered. Monitoring for hemorrhagic transformation. Neurology consult for post-TPA care.", department: "Neurology", vitals: { bp: "178/95", hr: 88, spo2: "96%" } } },
    { patientId: "P-1014", author: "Dr. Preeti Nair", data: { diagnosis: "Temporal Lobe Epilepsy", notes: "EEG shows left temporal sharp waves and intermittent rhythmic delta activity. MRI: left hippocampal sclerosis. Seizure semiology consistent with focal impaired awareness. Started on Levetiracetam 500mg BID. Driving restrictions advised.", department: "Neurology", vitals: { bp: "128/82", hr: 74, spo2: "97%" } } },
    { patientId: "P-1015", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Cervical Disc Herniation - C5/C6", notes: "MRI shows C5/C6 disc herniation with right foraminal stenosis and C6 nerve root compression. Patient has right arm pain and weakness (deltoid 4/5). Failed 6 weeks of conservative management. Scheduled for anterior cervical discectomy and fusion.", department: "Neurosurgery", vitals: { bp: "132/78", hr: 72, spo2: "97%" } } },
    { patientId: "P-1016", author: "Dr. Preeti Nair", data: { diagnosis: "Multiple Sclerosis - Relapsing Remitting", notes: "MRI brain shows 8 periventricular and juxtacortical T2/FLAIR lesions. Spinal cord: 2 cervical lesions. CSF: oligoclonal bands positive. First episode: optic neuritis and right hemiparesis. Started on high-dose IV methylprednisolone. Disease-modifying therapy discussion pending.", department: "Neurology", vitals: { bp: "120/76", hr: 68, spo2: "98%" } } },
    { patientId: "P-1017", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Chronic Subdural Hematoma", notes: "CT head shows right frontoparietal chronic SDH with 12mm midline shift. Patient presents with progressive headache and gait instability over 2 weeks. On anticoagulation (Warfarin) for AFib. Reversal of anticoagulation initiated. Burr hole drainage planned.", department: "Neurosurgery", vitals: { bp: "142/88", hr: 76, spo2: "95%" } } },
    { patientId: "P-1018", author: "Dr. Preeti Nair", data: { diagnosis: "Migraine with Aura", notes: "Patient experiences 2-3 episodes monthly with visual aura (scotoma, fortification spectra) lasting 20-30 minutes followed by severe hemicranial headache. Failed sumatriptan. Topiramate 50mg BID initiated. Headache diary provided.", department: "Neurology", vitals: { bp: "118/72", hr: 66, spo2: "98%" } } },
    { patientId: "P-1019", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Posterior Fossa Tumor - Suspected Meningioma", notes: "MRI shows 3.5cm extra-axial posterior fossa mass with dural tail sign, consistent with meningioma. Patient has 2-week history of progressive headache and papilledema. Neurosurgical resection planned. Pre-operative embolization being considered.", department: "Neurosurgery", vitals: { bp: "135/85", hr: 78, spo2: "96%" } } },
    { patientId: "P-1020", author: "Dr. Preeti Nair", data: { diagnosis: "Peripheral Neuropathy - Diabetic", notes: "Nerve conduction studies: sensory and motor axonal polyneuropathy in stocking-glove distribution. Patient has 15-year history of poorly controlled diabetes (HbA1c 9.2%). Started on Pregabalin for neuropathic pain. Diabetes optimization referred to Endocrinology.", department: "Neurology", vitals: { bp: "130/80", hr: 72, spo2: "97%" } } },
    { patientId: "P-1021", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Traumatic Brain Injury - Moderate", notes: "GCS 12 on arrival. CT head: small right frontal contusion, no midline shift. Managed conservatively in Neuro-ICU. Serial neurological observations. Post-traumatic amnesia noted. Neuropsychology referral for cognitive assessment.", department: "Neurosurgery", vitals: { bp: "145/90", hr: 92, spo2: "95%" } } },
    { patientId: "P-1022", author: "Dr. Preeti Nair", data: { diagnosis: "Myasthenia Gravis - Generalized", notes: "Repetitive nerve stimulation: 40% decrement at 3 Hz. AChR antibodies positive. CT chest: thymic hyperplasia. Ptosis and diplopia worse in evenings. Started on Pyridostigmine. Thymectomy consultation scheduled.", department: "Neurology", vitals: { bp: "122/74", hr: 80, spo2: "96%" } } },
    { patientId: "P-1023", author: "Dr. Arvind Swaminathan", data: { diagnosis: "Lumbar Spinal Stenosis - L4/L5", notes: "MRI shows severe central canal stenosis at L4/L5 with bilateral foraminal narrowing. Patient has neurogenic claudication: bilateral leg pain after walking 100 meters. Failed conservative management. Laminectomy and decompression planned.", department: "Neurosurgery", vitals: { bp: "138/82", hr: 74, spo2: "97%" } } },
    { patientId: "P-1024", author: "Dr. Preeti Nair", data: { diagnosis: "Bell's Palsy - Left", notes: "Acute onset left facial weakness (House-Brackmann Grade IV). No other neurological deficits. No trauma or ear pathology. Started on Prednisone 60mg daily tapering over 10 days. Eye protection measures initiated. Follow-up in 2 weeks.", department: "Neurology", vitals: { bp: "125/76", hr: 70, spo2: "98%" } } }
  ],
  "Orthopaedics & Joint Replacement": [
    { patientId: "P-1025", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Right Total Knee Replacement", notes: "Severe OA right knee (Kellgren-Lawrence Grade 4). Failed medical management. Pre-operative templating done. Patient positioning: supine. Approach: medial parapatellar. Implant: posterior stabilized cemented. Intra-operative blood loss: 250mL. Procedure uncomplicated.", department: "Orthopaedics", vitals: { bp: "128/78", hr: 72, spo2: "99%" } } },
    { patientId: "P-1026", author: "Dr. Neha Kulkarni", data: { diagnosis: "Left Rotator Cuff Tear - Full Thickness", notes: "MRI shows full-thickness tear of supraspinatus tendon with 2cm retraction. Failed 3 months of physiotherapy. Arthroscopic repair performed: single-row technique with suture anchors. Post-op: sling for 6 weeks, passive ROM initiated day 1.", department: "Orthopaedics", vitals: { bp: "122/74", hr: 68, spo2: "98%" } } },
    { patientId: "P-1027", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Left Total Hip Replacement", notes: "Severe AVN of left femoral head (Ficat Stage III). Young patient (52 years). Used ceramic-on-ceramic bearing with cementless acetabular cup and cementless femoral stem. Leg length equalized. Post-op X-ray satisfactory.", department: "Orthopaedics", vitals: { bp: "130/82", hr: 76, spo2: "97%" } } },
    { patientId: "P-1028", author: "Dr. Neha Kulkarni", data: { diagnosis: "ACL Reconstruction - Right Knee", notes: "Complete ACL tear with Grade II MCL sprain. Reconstruction performed using hamstring autograft (semitendinosus and gracilis). Femoral tunnel: outside-in technique. Graft fixation: interference screws. Post-op brace locked in extension for 2 weeks.", department: "Orthopaedics", vitals: { bp: "120/70", hr: 66, spo2: "98%" } } },
    { patientId: "P-1029", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Open Fracture Right Tibia (Gustilo II)", notes: "Road traffic accident. 4cm wound with moderate soft tissue damage. Bone visible. Irrigation and debridement performed. External fixator applied as damage control. IV antibiotics started. Definitive fixation with intramedullary nail planned after soft tissue settles.", department: "Orthopaedics", vitals: { bp: "108/68", hr: 105, spo2: "96%" } } },
    { patientId: "P-1030", author: "Dr. Neha Kulkarni", data: { diagnosis: "Carpal Tunnel Syndrome - Bilateral", notes: "Nerve conduction studies: severe bilateral median nerve compression at wrist. Symptoms: numbness in thumb, index, middle fingers, night pain. Failed splinting. Bilateral endoscopic carpal tunnel release performed under local anesthesia.", department: "Orthopaedics", vitals: { bp: "125/76", hr: 70, spo2: "97%" } } },
    { patientId: "P-1031", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Achilles Tendon Rupture - Left", notes: "Complete rupture 3cm above insertion. Thompson test positive. Managed conservatively with functional bracing (Vacoped boot) for 6 weeks. Gradual return to weight-bearing. Physiotherapy protocol initiated.", department: "Orthopaedics", vitals: { bp: "132/80", hr: 74, spo2: "97%" } } },
    { patientId: "P-1032", author: "Dr. Neha Kulkarni", data: { diagnosis: "Dupuytren's Contracture - Right Hand", notes: "Progressive flexion contracture of right ring and small fingers (80 degrees at MCP). Positive family history. Collagenase injection (Xiaflex) performed. Post-injection manipulation achieved full extension. Splinting at night for 6 months.", department: "Orthopaedics", vitals: { bp: "118/72", hr: 68, spo2: "98%" } } },
    { patientId: "P-1033", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Osteoporotic Compression Fracture - L1", notes: "DXA scan: T-score -3.8 at lumbar spine. Minimal trauma fall resulted in L1 wedge compression fracture. Kyphoplasty performed: bilateral pedicle approach, balloon inflation, cement injection. Pain relief immediate. Started on Denosumab.", department: "Orthopaedics", vitals: { bp: "135/82", hr: 72, spo2: "96%" } } },
    { patientId: "P-1034", author: "Dr. Neha Kulkarni", data: { diagnosis: "Frozen Shoulder - Right", notes: "Progressive shoulder pain and stiffness for 4 months. Range of motion: forward flexion 90°, abduction 80°, external rotation 10°. MRI: thickened rotator interval capsule. Under anesthesia manipulation performed. Aggressive physiotherapy initiated.", department: "Orthopaedics", vitals: { bp: "128/78", hr: 76, spo2: "97%" } } },
    { patientId: "P-1035", author: "Dr. Vikramaditya Rathore", data: { diagnosis: "Revision Total Knee Replacement", notes: "Previous TKA (2018) with aseptic loosening. Revision using stemmed components with augments for bone loss. Constrained condylar knee implant used. Intra-operative findings: significant polyethylene wear and osteolysis. Allograft bone used for defect filling.", department: "Orthopaedics", vitals: { bp: "140/85", hr: 88, spo2: "95%" } } },
    { patientId: "P-1036", author: "Dr. Neha Kulkarni", data: { diagnosis: "Ganglion Cyst - Left Wrist", notes: "Dorsal wrist mass, 2.5cm, transilluminating. Aspiration yielded thick clear fluid. Recurrence after previous aspiration. Excision performed, pedicle traced to scapholunate ligament. Histology confirmed benign ganglion. Low recurrence expected.", department: "Orthopaedics", vitals: { bp: "120/74", hr: 66, spo2: "98%" } } }
  ],
  "Pediatrics & Neonatology": [
    { patientId: "P-1037", author: "Dr. Amit Mehra", data: { diagnosis: "Acute Viral Bronchiolitis", notes: "8-month-old with 3-day history of cough, nasal discharge, and increased work of breathing. RSV positive. SpO2 92% on room air. Nares flaring, subcostal retractions. Managed with nasal suctioning and supplemental oxygen. Monitor for respiratory deterioration.", department: "Pediatrics", vitals: { temp: "38.4°C", hr: 165, rr: 52, spo2: "92%" } } },
    { patientId: "P-1038", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Neonatal Sepsis - Late Onset", notes: "3-week-old with fever (38.8°C), poor feeding, and lethargy. Blood culture pending. Started on Ampicillin + Gentamicin pending culture results. CRP elevated at 45 mg/L. LP performed: CSF clear, cell count normal. Monitor closely.", department: "Neonatology", vitals: { temp: "38.8°C", hr: 180, rr: 58, spo2: "94%" } } },
    { patientId: "P-1039", author: "Dr. Amit Mehra", data: { diagnosis: "Kawasaki Disease - Incomplete", notes: "5-year-old with fever >5 days, bilateral non-purulent conjunctivitis, cracked lips, and strawberry tongue. ESR 92, CRP 120. Echo: small RCA aneurysm (3.2mm). Started on IVIG 2g/kg and high-dose Aspirin. Continue monitoring for coronary changes.", department: "Pediatrics", vitals: { temp: "39.6°C", hr: 130, rr: 28, spo2: "97%" } } },
    { patientId: "P-1040", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Neonatal Jaundice - Physiological", notes: "Day 2 of life. TSB 12 mg/dL at 48 hours. Exclusively breastfed. Bilirubin on Bhutani hour-specific chart: low-intermediate risk zone. Phototherapy initiated. Adequate hydration ensured. Repeat TSB in 12 hours.", department: "Neonatology", vitals: { temp: "36.8°C", hr: 140, rr: 42, spo2: "98%" } } },
    { patientId: "P-1041", author: "Dr. Amit Mehra", data: { diagnosis: "Febrile Seizure - Simple", notes: "2-year-old with first febrile seizure lasting 3 minutes. Post-ictal state for 20 minutes. Temperature 39.8°C. Otitis media identified as source. CT head normal. Neurological examination normal post-recovery. Parent education on seizure management provided.", department: "Pediatrics", vitals: { temp: "39.8°C", hr: 145, rr: 32, spo2: "97%" } } },
    { patientId: "P-1042", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Respiratory Distress Syndrome - Premature", notes: "Born at 30 weeks. Required intubation and surfactant replacement (Curosurf 100mg/kg). Currently on CPAP. Chest X-ray: ground glass opacity bilaterally. Caffeine citrate started for apnea of prematurity. Target SpO2 90-95%.", department: "Neonatology", vitals: { temp: "36.6°C", hr: 155, rr: 65, spo2: "93%" } } },
    { patientId: "P-1043", author: "Dr. Amit Mehra", data: { diagnosis: "Childhood Asthma - Moderate Persistent", notes: "6-year-old with recurrent wheezing, nocturnal cough, and exercise intolerance. Spirometry: FEV1 68% predicted. Reversible airway obstruction: 15% improvement post-bronchodilator. Started on Fluticasone 125mcg BID + Salbutamol PRN. Asthma action plan provided.", department: "Pediatrics", vitals: { temp: "37.0°C", hr: 98, rr: 26, spo2: "95%" } } },
    { patientId: "P-1044", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Necrotizing Enterocolitis - Stage II", notes: "Premature infant (28 weeks), day 14. Abdominal distension, bloody stools. Pneumatosis intestinalis on abdominal X-ray. NPO, nasogastric decompression, IV fluids, and broad-spectrum antibiotics (Meropenem + Vancomycin) started. Surgical consultation obtained.", department: "Neonatology", vitals: { temp: "37.2°C", hr: 172, rr: 55, spo2: "91%" } } },
    { patientId: "P-1045", author: "Dr. Amit Mehra", data: { diagnosis: "Iron Deficiency Anemia", notes: "18-month-old with pallor, irritability, and poor appetite. Hb 7.2 g/dL, MCV 62 fL, ferritin 6 ng/mL. Peripheral smear: microcytic hypochromic RBCs. Started on Ferrous sulfate 3mg/kg/day. Dietary counseling provided. Follow-up in 4 weeks.", department: "Pediatrics", vitals: { temp: "37.1°C", hr: 110, rr: 24, spo2: "98%" } } },
    { patientId: "P-1046", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Retinopathy of Prematurity - Stage 2", notes: "ROP screening at 32 weeks corrected age: bilateral Stage 2 ROP with plus disease in Zone II. Laser photocoagulation performed in both eyes. Follow-up examination scheduled in 1 week to assess response.", department: "Neonatology", vitals: { temp: "36.7°C", hr: 148, rr: 44, spo2: "94%" } } },
    { patientId: "P-1047", author: "Dr. Amit Mehra", data: { diagnosis: "Type 1 Diabetes Mellitus - New Onset", notes: "9-year-old with 2-week polyuria, polydipsia, and weight loss. Blood glucose 340 mg/dL, HbA1c 11.2%. Urine ketones positive. Started on basal-bolus insulin regimen (Glargine + Aspart). Carb counting education initiated. DKA protocol on standby.", department: "Pediatrics", vitals: { temp: "37.3°C", hr: 115, rr: 22, spo2: "98%" } } },
    { patientId: "P-1048", author: "Dr. Shalini Deshmukh", data: { diagnosis: "Transient Tachypnea of Newborn", notes: "Term infant born via elective C-section. Respiratory distress at 2 hours of age. Chest X-ray: perihilar streaking, fluid in fissures. Managed with supplemental O2 via nasal cannula. Resolved by 48 hours. Ready for discharge.", department: "Neonatology", vitals: { temp: "36.9°C", hr: 135, rr: 55, spo2: "96%" } } }
  ],
  "Obstetrics & Gynecology": [
    { patientId: "P-1049", author: "Dr. Ananya Sen", data: { diagnosis: "Gestational Diabetes Mellitus", notes: "28-year-old G2P1 at 26 weeks. GTT: fasting 108, 1hr 198, 2hr 165. Started on diet control and glucose monitoring QID. Fetal growth scan at 32 weeks showed normal amniotic fluid. If not controlled on diet, insulin therapy will be initiated.", department: "OB-GYN", vitals: { bp: "118/72", wt: "68kg", fundal_height: "26cm" } } },
    { patientId: "P-1050", author: "Dr. Ritu Bhargava", data: { diagnosis: "Endometriosis - Stage III", notes: "32-year-old with chronic pelvic pain, dysmenorrhea, and dyspareunia. Diagnostic laparoscopy: endometriotic lesions on bilateral ovaries, posterior cul-de-sac, and uterosacral ligaments. Ovarian cyst (chocolate cyst 4cm) on left ovary. Excision performed. Started on GnRH agonist.", department: "OB-GYN", vitals: { bp: "120/76", hr: 72 } } },
    { patientId: "P-1051", author: "Dr. Ananya Sen", data: { diagnosis: "Preeclampsia - Severe", notes: "34-year-old G1P0 at 34 weeks. BP 168/108, proteinuria 3+. Headache, visual disturbances. LFTs elevated: AST 85. Platelets 98,000. Indicated for delivery. IV MgSO4 for seizure prophylaxis. Cesarean section performed. Baby: 2.1kg, Apgar 7/9.", department: "OB-GYN", vitals: { bp: "168/108", hr: 95, urine_protein: "3+" } } },
    { patientId: "P-1052", author: "Dr. Ritu Bhargava", data: { diagnosis: "Uterine Fibroids - Symptomatic", notes: "42-year-old with menorrhagia causing iron deficiency anemia (Hb 8.5g/dL). Ultrasound: multiple fibroids, largest 8cm submucosal. Failed medical management. Scheduled for hysteroscopic myomectomy of submucosal fibroid. UAE considered for remaining intramural fibroids.", department: "OB-GYN", vitals: { bp: "125/78", hr: 82, hb: "8.5g/dL" } } },
    { patientId: "P-1053", author: "Dr. Ananya Sen", data: { diagnosis: "Ectopic Pregnancy - Left Tube", notes: "28-year-old with 6 weeks amenorrhea and left lower abdominal pain. β-hCG 2800 mIU/mL, not rising appropriately. TVS: left adnexal mass with no intrauterine pregnancy. Tubal rupture imminent. Emergency laparoscopy: left salpingectomy performed. Blood loss 400mL.", department: "OB-GYN", vitals: { bp: "100/65", hr: 110, hb: "10.2g/dL" } } },
    { patientId: "P-1054", author: "Dr. Ritu Bhargava", data: { diagnosis: "Polycystic Ovarian Syndrome (PCOS)", notes: "24-year-old with oligomenorrhea, hirsutism, and acne. Ultrasound: bilateral polycystic ovaries. Labs: elevated testosterone, LH:FSH ratio 3:1. Started on Metformin 500mg BID and OCP for cycle regulation. Lifestyle modification counseling provided.", department: "OB-GYN", vitals: { bp: "115/72", hr: 68, bmi: "31.2" } } },
    { patientId: "P-1055", author: "Dr. Ananya Sen", data: { diagnosis: "Placenta Previa - Complete", notes: "35-year-old G4P2 at 32 weeks. Painless vaginal bleeding. TVS: placenta completely covering internal os. Admitted for observation. Antenatal corticosteroids administered for fetal lung maturity. Planned cesarean delivery at 37 weeks. Blood crossmatch done.", department: "OB-GYN", vitals: { bp: "122/74", hr: 88, fundal_height: "32cm" } } },
    { patientId: "P-1056", author: "Dr. Ritu Bhargava", data: { diagnosis: "Ovarian Cyst - Complex", notes: "45-year-old with incidental finding of 7cm complex ovarian cyst on routine ultrasound. Mixed echogenicity, solid component with vascularity. Tumor markers: CA-125 45 U/mL, HE4 normal. Risk of malignancy index: low. Diagnostic laparoscopy and cystectomy planned.", department: "OB-GYN", vitals: { bp: "128/78", hr: 74 } } },
    { patientId: "P-1057", author: "Dr. Ananya Sen", data: { diagnosis: "Postpartum Hemorrhage", notes: "30-year-old, G2P2, 2 hours post normal vaginal delivery. PPH due to uterine atony. Active management of third stage performed. Uterine massage, oxytocin, carboprost, and tranexamic acid administered. Estimated blood loss 1200mL. 2 units PRBC transfused. Stable.", department: "OB-GYN", vitals: { bp: "95/60", hr: 115, hb: "8.8g/dL" } } },
    { patientId: "P-1058", author: "Dr. Ritu Bhargava", data: { diagnosis: "Cervical Dysplasia - HSIL (CIN II/III)", notes: "33-year-old with HSIL on Pap smear. Colposcopy: acetowhite changes in transformation zone. Biopsy confirmed CIN II/III. LEEP procedure performed. Margins clear. HPV 16 positive. Follow-up Pap in 12 months.", department: "OB-GYN", vitals: { bp: "118/72", hr: 70 } } },
    { patientId: "P-1059", author: "Dr. Ananya Sen", data: { diagnosis: "Fibroid Uterus with Infertility", notes: "36-year-old attempting conception for 2 years. Large 6cm intramural fibroid distorting endometrial cavity. Hysteroscopic myomectomy performed. Uterine cavity restored. Post-op: IUI planned after 3 months recovery. Fertility counseling provided.", department: "OB-GYN", vitals: { bp: "120/76", hr: 68 } } },
    { patientId: "P-1060", author: "Dr. Ritu Bhargava", data: { diagnosis: "Pelvic Inflammatory Disease", notes: "26-year-old with lower abdominal pain, fever, and abnormal discharge. Cervical culture: Chlamydia positive. Ultrasound: bilateral tubal thickening, free fluid. Treated with Ceftriaxone 250mg IM + Doxycycline 100mg BID x 14 days. Partner notified and treated.", department: "OB-GYN", vitals: { temp: "38.6°C", bp: "115/70", hr: 92 } } }
  ],
  "General & Laparoscopic Surgery": [
    { patientId: "P-1061", author: "Dr. Harish Chandra", data: { diagnosis: "Laparoscopic Cholecystectomy - Acute Cholecystitis", notes: "45-year-old with acute cholecystitis. USG: gallbladder wall thickening, pericholecystic fluid, multiple stones. WBC 14,000. Started on IV antibiotics. Laparoscopic cholecystectomy performed within 72 hours. Critical view of safety achieved. Calot's triangle cleared. No bile leak. Discharged day 1.", department: "General Surgery", vitals: { temp: "38.2°C", bp: "128/80", hr: 88 } } },
    { patientId: "P-1062", author: "Dr. Pooja Joshi", data: { diagnosis: "Inguinal Hernia - Right Direct", notes: "58-year-old male with right groin bulge, reducible. Lichtenstein tension-free mesh repair performed under local anesthesia. 15x10cm polypropylene mesh placed. Procedure uncomplicated. Day case procedure. Return to normal activities in 1 week.", department: "General Surgery", vitals: { bp: "130/82", hr: 72 } } },
    { patientId: "P-1063", author: "Dr. Harish Chandra", data: { diagnosis: "Acute Appendicitis", notes: "22-year-old with 18-hour history of right iliac fossa pain, anorexia, nausea. Alvarado score: 8. CT abdomen: acute appendicitis with appendicolith. Laparoscopic appendectomy performed. Appendix gangrenous but not perforated. Mesenteric vessel ligation with clips. Discharged day 1.", department: "General Surgery", vitals: { temp: "38.0°C", bp: "118/74", hr: 92 } } },
    { patientId: "P-1064", author: "Dr. Pooja Joshi", data: { diagnosis: "Incisional Hernia", notes: "62-year-old with hernia at previous laparotomy scar. CT: 5cm fascial defect. Laparoscopic IPOM repair performed. Composite mesh placed with adequate overlap. 5-year recurrence risk discussed. Activity restrictions for 6 weeks.", department: "General Surgery", vitals: { bp: "135/85", hr: 76 } } },
    { patientId: "P-1065", author: "Dr. Harish Chandra", data: { diagnosis: "Laparoscopic Appendectomy - Complicated", notes: "35-year-old with perforated appendicitis and localized abscess. Pre-operative drainage of abscess performed by interventional radiology. Interval appendectomy performed 6 weeks later. Adhesions noted. Operation completed laparoscopically.", department: "General Surgery", vitals: { temp: "37.4°C", bp: "122/78", hr: 78 } } },
    { patientId: "P-1066", author: "Dr. Pooja Joshi", data: { diagnosis: "Umbilical Hernia", notes: "40-year-old with reducible umbilical hernia, 2cm defect. Hernia repair with mesh (onlay technique). Day case procedure. Post-operative instructions: no heavy lifting for 4 weeks. Wound care instructions provided.", department: "General Surgery", vitals: { bp: "125/76", hr: 70 } } },
    { patientId: "P-1067", author: "Dr. Harish Chandra", data: { diagnosis: "Laparoscopic Fundoplication - GERD", notes: "48-year-old with refractory GERD despite high-dose PPI. 24-hour pH study: DeMeester score 45. Manometry: normal motility. Laparoscopic Nissen fundoplication performed. 360-degree wrap. Short gastric vessels divided. Dysphagia expected to resolve in 6 weeks.", department: "General Surgery", vitals: { bp: "128/80", hr: 72 } } },
    { patientId: "P-1068", author: "Dr. Pooja Joshi", data: { diagnosis: "Excision of Breast Lump - Fibroadenoma", notes: "22-year-old with 2cm mobile breast lump. Mammography: BI-RADS 3. Ultrasound: well-defined hypoechoic mass, likely fibroadenoma. Excision biopsy performed under local anesthesia. Histopathology: confirmed fibroadenoma. Margins clear.", department: "General Surgery", vitals: { bp: "118/72", hr: 68 } } },
    { patientId: "P-1069", author: "Dr. Harish Chandra", data: { diagnosis: "Strangulated Femoral Hernia", notes: "72-year-old female with irreducible groin lump, pain, vomiting. CT: strangulated femoral hernia with transition point. Emergency surgery: femoral hernia repair with mesh. Bowel viability confirmed. Small bowel resection not required. Post-op monitoring in surgical ward.", department: "General Surgery", vitals: { bp: "140/90", hr: 105, spo2: "94%" } } },
    { patientId: "P-1070", author: "Dr. Pooja Joshi", data: { diagnosis: "Hemorrhoids - Grade III", notes: "52-year-old with recurrent bleeding and prolapse. Colonoscopy: normal. Anoscopy: Grade III hemorrhoids at 3, 7, 11 o'clock positions. Stapled hemorrhoidopexy (PPH) performed. Post-operative pain managed with oral analgesics. Follow-up in 2 weeks.", department: "General Surgery", vitals: { bp: "132/82", hr: 74 } } },
    { patientId: "P-1071", author: "Dr. Harish Chandra", data: { diagnosis: "Ventral Hernia - Epigastric", notes: "45-year-old with epigastric hernia, 3cm defect. Mesh repair (sublay technique) performed. Post-operative: wound care, no heavy lifting for 6 weeks. Follow-up in 1 week for wound check.", department: "General Surgery", vitals: { bp: "126/78", hr: 72 } } },
    { patientId: "P-1072", author: "Dr. Pooja Joshi", data: { diagnosis: "Laparoscopic Sigmoid Colectomy - Diverticular Disease", notes: "58-year-old with recurrent sigmoid diverticulitis (3 episodes in 1 year). CT: sigmoid thickening, pericolonic fat stranding. Laparoscopic anterior resection performed. Specimen: 25cm sigmoid with diverticula. Anastomosis: stapled, tension-free. Leak test negative.", department: "General Surgery", vitals: { bp: "130/80", hr: 76 } } }
  ],
  "Internal Medicine": [
    { patientId: "P-1073", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Type 2 Diabetes Mellitus - Uncontrolled", notes: "55-year-old with HbA1c 10.2%. Currently on Metformin 1000mg BID. Fasting glucose 245 mg/dL. BMI 32. Started on Empagliflozin 10mg + Linagliptin 5mg. Insulin initiation discussed if targets not met in 3 months. Diabetic foot exam: normal. Retinopathy screening due.", department: "Internal Medicine", vitals: { bp: "142/88", hr: 78, fasting_glucose: "245mg/dL" } } },
    { patientId: "P-1074", author: "Dr. Kavita Hegde", data: { diagnosis: "Community Acquired Pneumonia", notes: "65-year-old with 3-day fever, cough with purulent sputum, dyspnea. Chest X-ray: right lower lobe consolidation. CRP 120, Procalcitonin 2.5. CURB-65 score: 2. Admitted for IV Ceftriaxone + Azithromycin. Oxygen supplementation via nasal cannula. Monitor clinical response.", department: "Internal Medicine", vitals: { temp: "39.2°C", bp: "118/72", hr: 105, spo2: "91%" } } },
    { patientId: "P-1075", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Hypertension - Resistant", notes: "58-year-old on triple therapy (Amlodipine 10mg, Telmisartan 80mg, Chlorthalidone 25mg) with BP still 152/95. Ambulatory BP monitoring confirmed. Secondary causes excluded: normal renal arteries, normal aldosterone/renin ratio. Added Spironolactone 25mg. Salt restriction reinforced.", department: "Internal Medicine", vitals: { bp: "152/95", hr: 76 } } },
    { patientId: "P-1076", author: "Dr. Kavita Hegde", data: { diagnosis: "Urinary Tract Infection - Complicated", notes: "70-year-old female with dysuria, frequency, and fever. Urine culture: E. coli >100,000 CFU/mL, sensitive to Nitrofurantoin and Ciprofloxacin. Creatinine 1.4 (baseline 0.9). Treated with Ciprofloxacin 500mg BID x 7 days. Renal ultrasound to rule out obstruction.", department: "Internal Medicine", vitals: { temp: "38.8°C", bp: "130/80", hr: 88 } } },
    { patientId: "P-1077", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Hyperthyroidism - Graves' Disease", notes: "35-year-old with weight loss, tremor, palpitations, and heat intolerance. TSH <0.01, Free T4 4.2. TSI positive. Radioactive iodine uptake: diffuse increase. Started on Carbimazole 20mg TID. Beta-blocker (Propranolol) for symptom control. Thyroid function monitoring every 6 weeks.", department: "Internal Medicine", vitals: { bp: "140/65", hr: 110, weight: "52kg" } } },
    { patientId: "P-1078", author: "Dr. Kavita Hegde", data: { diagnosis: "Chronic Kidney Disease - Stage 3b", notes: "68-year-old with CKD from diabetes. Creatinine 2.8, eGFR 32. Proteinuria 800mg/24hr. Started on SGLT2 inhibitor (Dapagliflozin 10mg) for renal protection. ACE inhibitor continued. Anemia managed with Epoetin alfa. Nephrology follow-up every 3 months.", department: "Internal Medicine", vitals: { bp: "135/82", hr: 72, creatinine: "2.8" } } },
    { patientId: "P-1079", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Acute Gastroenteritis", notes: "28-year-old with 2-day history of diarrhea (8 episodes), vomiting, and abdominal cramps. Likely viral etiology. No blood in stool. Mild dehydration. Oral rehydration therapy initiated. Anti-emetic (Ondansetron) for nausea. BRAT diet. Stool culture sent.", department: "Internal Medicine", vitals: { temp: "37.8°C", bp: "110/68", hr: 95 } } },
    { patientId: "P-1080", author: "Dr. Kavita Hegde", data: { diagnosis: "COPD Exacerbation", notes: "62-year-old with known COPD (GOLD Stage III). Acute exacerbation with increased sputum production and dyspnea. PEF 180 L/min (personal best 300). Started on Nebulized Salbutamol + Ipratropium, IV Methylprednisolone, and Oral Azithromycin. Non-invasive ventilation if deteriorates.", department: "Internal Medicine", vitals: { temp: "37.6°C", bp: "138/85", hr: 98, spo2: "89%" } } },
    { patientId: "P-1081", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Hypothyroidism", notes: "45-year-old female with fatigue, weight gain, constipation, and dry skin. TSH 18.5, Free T4 0.6. TPO antibodies positive. Started on Levothyroxine 75mcg daily, empty stomach 30 minutes before breakfast. Recheck TSH in 6 weeks.", department: "Internal Medicine", vitals: { bp: "125/80", hr: 62, weight: "78kg" } } },
    { patientId: "P-1082", author: "Dr. Kavita Hegde", data: { diagnosis: "DVT - Left Lower Extremity", notes: "40-year-old with onset calf pain and swelling after long flight. D-dimer elevated. Duplex ultrasound: DVT in left popliteal vein. Started on Rivaroxaban 15mg BID x 21 days then 20mg daily. Compression stockings. Avoid prolonged immobility. Follow-up in 1 week.", department: "Internal Medicine", vitals: { bp: "128/78", hr: 80, spo2: "97%" } } },
    { patientId: "P-1083", author: "Dr. Sanjay Nambiar", data: { diagnosis: "Sepsis - Urinary Source", notes: "72-year-old with confusion, fever, and rigors. Blood pressure 88/55. Lactate 3.8. Urine: frank pus. Blood cultures drawn. Started on aggressive fluid resuscitation and empirical Meropenem. Vasopressor (Norepinephrine) initiated. Admitted to ICU. Source control: urinary catheter placed.", department: "Internal Medicine", vitals: { temp: "39.8°C", bp: "88/55", hr: 120, lactate: "3.8" } } },
    { patientId: "P-1084", author: "Dr. Kavita Hegde", data: { diagnosis: "Anemia - Iron Deficiency", notes: "30-year-old vegetarian female with fatigue and pallor. Hb 9.2 g/dL, MCV 68 fL, Ferritin 8 ng/mL. Stool occult blood negative. Started on Ferrous fumarate 210mg TID. Vitamin C supplementation for absorption. Dietary counseling: increase leafy greens, legumes. Follow-up in 4 weeks.", department: "Internal Medicine", vitals: { bp: "110/68", hr: 88, hb: "9.2g/dL" } } }
  ],
  "Oncology": [
    { patientId: "P-1085", author: "Dr. Siddharth Menon", data: { diagnosis: "Invasive Ductal Carcinoma - Left Breast (Stage IIA)", notes: "52-year-old female. Core biopsy: Invasive ductal carcinoma, grade 2, ER+/PR+/HER2-. T2N0M0. Plan: Neoadjuvant chemotherapy (AC-T regimen) x 4 cycles. Fertility preservation discussed. Genetic counseling for BRCA testing. MRI left breast: 2.8cm lesion.", department: "Oncology", vitals: { bp: "125/78", hr: 72 } } },
    { patientId: "P-1086", author: "Dr. Maya Pillai", data: { diagnosis: "Right Hemicolectomy - Cecal Adenocarcinoma", notes: "65-year-old male. Colonoscopy: 4cm ulcerated mass in cecum. CT abdomen: no metastasis. Pre-operative staging: T3N1M0 (Stage IIIB). Right hemicolectomy performed laparoscopically. 12 lymph nodes harvested, 2 positive. Adjuvant chemotherapy (FOLFOX) planned.", department: "Oncology", vitals: { bp: "132/82", hr: 76 } } },
    { patientId: "P-1087", author: "Dr. Siddharth Menon", data: { diagnosis: "Non-Small Cell Lung Cancer - Adenocarcinoma (Stage IV)", notes: "58-year-old smoker. CT chest: 3cm right upper lobe mass with mediastinal lymphadenopathy. Brain MRI: single small cerebral metastasis. Biopsy: adenocarcinoma, EGFR mutation positive (Exon 19 deletion). Started on Osimertinib 80mg daily. Palliative radiation for brain lesion.", department: "Oncology", vitals: { bp: "128/80", hr: 82, spo2: "94%" } } },
    { patientId: "P-1088", author: "Dr. Maya Pillai", data: { diagnosis: "Thyroid Carcinoma - Papillary", notes: "45-year-old female. Incidental thyroid nodule on ultrasound. FNA: papillary thyroid carcinoma. Total thyroidectomy performed with central lymph node dissection. Pathology: 1.5cm tumor, no lymph node metastasis. Radioactive iodine ablation planned. Lifelong Levothyroxine.", department: "Oncology", vitals: { bp: "120/76", hr: 68 } } },
    { patientId: "P-1089", author: "Dr. Siddharth Menon", data: { diagnosis: "Colorectal Liver Metastases", notes: "55-year-old with metachronous liver metastases from sigmoid colon cancer (resected 8 months ago). CT: 3 metastases in right lobe, largest 4cm. CEA elevated at 28. FOLFOX chemotherapy x 6 cycles. Interdisciplinary discussion: borderline resectable. Repeat imaging in 8 weeks.", department: "Oncology", vitals: { bp: "125/78", hr: 74 } } },
    { patientId: "P-1090", author: "Dr. Maya Pillai", data: { diagnosis: "Gastrointestinal Stromal Tumor (GIST) - Gastric", notes: "62-year-old with incidental gastric mass on endoscopy. EUS-guided biopsy: GIST, CD117 positive. CT: 5cm exophytic gastric mass, no metastasis. Laparoscopic wedge gastrectomy performed. Risk stratification: intermediate risk. Imatinib 400mg daily adjuvant therapy for 3 years.", department: "Oncology", vitals: { bp: "130/80", hr: 72 } } },
    { patientId: "P-1091", author: "Dr. Siddharth Menon", data: { diagnosis: "Chronic Lymphocytic Leukemia (CLL) - Rai Stage I", notes: "68-year-old male with incidental lymphocytosis. WBC 45,000, lymphocytes 32,000. Flow cytometry: monoclonal B-cell population, CD5+/CD19+/CD23+. FISH: del(13q). Watch and wait approach. No treatment indications currently. Follow-up in 3 months.", department: "Oncology", vitals: { bp: "135/82", hr: 76 } } },
    { patientId: "P-1092", author: "Dr. Maya Pillai", data: { diagnosis: "Endometrial Carcinoma - Grade 1", notes: "58-year-old post-menopausal bleeding. Pipelle biopsy: endometrioid adenocarcinoma, grade 1. MRI: no myometrial invasion. Total abdominal hysterectomy, bilateral salpingo-oophorectomy, and pelvic lymphadenectomy performed. Final: Stage IA. No adjuvant therapy needed.", department: "Oncology", vitals: { bp: "128/78", hr: 70 } } },
    { patientId: "P-1093", author: "Dr. Siddharth Menon", data: { diagnosis: "Multiple Myeloma - ISS Stage II", notes: "63-year-old with back pain, anemia, and elevated calcium. Serum protein electrophoresis: M-spike 2.5g/dL. Bone marrow biopsy: 35% plasma cells. Beta-2 microglobulin 5.2. Albumin 3.2. Started on VRd regimen (Bortezomib, Lenalidomide, Dexamethasone). Stem cell transplant evaluation.", department: "Oncology", vitals: { bp: "122/76", hr: 80, hb: "9.8g/dL" } } },
    { patientId: "P-1094", author: "Dr. Maya Pillai", data: { diagnosis: "Gallbladder Carcinoma - Incidental Finding", notes: "45-year-old female, post-cholecystectomy for 'cholelithiasis'. Pathology: incidental gallbladder carcinoma, T2. Radical second-look surgery performed: bile duct resection, hepatic bed resection, lymph node dissection. Final: pT2N0M0. Adjuvant chemotherapy with Gemcitabine + Cisplatin.", department: "Oncology", vitals: { bp: "120/74", hr: 72 } } },
    { patientId: "P-1095", author: "Dr. Siddharth Menon", data: { diagnosis: "Head & Neck Cancer - Oral Cavity (Stage III)", notes: "50-year-old with tobacco chewer. Ulcerative lesion on left lateral tongue, 3cm. Biopsy: squamous cell carcinoma. CT neck: level II lymph node involvement. Planned: Transoral resection with left neck dissection + adjuvant chemoradiation (Cisplatin + RT). Speech pathology referral.", department: "Oncology", vitals: { bp: "135/85", hr: 82 } } },
    { patientId: "P-1096", author: "Dr. Maya Pillai", data: { diagnosis: "Hepatocellular Carcinoma - Early Stage", notes: "62-year-old male with chronic Hepatitis B. AFP elevated at 450. CT liver: 3.5cm solitary lesion in segment VI, arterial enhancement with washout. BCLC Stage A. Candidate for surgical resection. Hepatic function preserved (Child-Pugh A). Right hepatectomy planned.", department: "Oncology", vitals: { bp: "128/80", hr: 74 } } }
  ],
  "Dermatology & Cosmetology": [
    { patientId: "P-1097", author: "Dr. Tanya Kapoor", data: { diagnosis: "Psoriasis - Chronic Plaque", notes: "35-year-old with 5-year history of well-demarcated erythematous plaques with silvery scale on elbows, knees, and scalp. BSA 12%. PASI score 14. Started on Methotrexate 15mg weekly + Folic acid. Topical betamethasone for localized lesions. Phototherapy if no response in 3 months.", department: "Dermatology", vitals: { bp: "120/76", hr: 68 } } },
    { patientId: "P-1098", author: "Dr. Rohan Chawla", data: { diagnosis: "Acne Vulgaris - Moderate", notes: "19-year-old with comedonal and inflammatory acne on face for 2 years. Previous treatment with topical retinoids insufficient. Started on Isotretinoin 0.5mg/kg/day, titrating to 1mg/kg. Baseline labs: LFTs, lipids, CBC. Pregnancy prevention counseling. Monthly follow-up.", department: "Dermatology", vitals: { bp: "118/72", hr: 68 } } },
    { patientId: "P-1099", author: "Dr. Tanya Kapoor", data: { diagnosis: "Melanoma - Superficial Spreading (Stage IB)", notes: "42-year-old with changing mole on back. Excision biopsy: melanoma, Breslow thickness 1.2mm, no ulceration. Wide local excision with 2cm margins performed. Sentinel lymph node biopsy: negative. Follow-up: skin exams every 3 months, consider adjuvant therapy if high-risk features.", department: "Dermatology", vitals: { bp: "122/74", hr: 72 } } },
    { patientId: "P-1100", author: "Dr. Rohan Chawla", data: { diagnosis: "Rosacea - Erythematotelangiectatic", notes: "48-year-old female with persistent facial erythema and telangiectasias on cheeks and nose. Flushed easily with sun exposure and spicy food. Started on topical Ivermectin 1% cream. Sunscreen SPF 50 daily. Avoid triggers: alcohol, extreme temperatures. Laser therapy for telangiectasias planned.", department: "Dermatology", vitals: { bp: "118/72", hr: 66 } } },
    { patientId: "P-1101", author: "Dr. Tanya Kapoor", data: { diagnosis: "Contact Dermatitis - Allergic", notes: "30-year-old with itchy, vesicular rash on hands following new jewelry. Patch testing positive for Nickel. Allergic contact dermatitis confirmed. Avoidance of nickel-containing items. Potent topical steroid (Clobetasol) for acute phase. Emollients for barrier repair. Follow-up in 4 weeks.", department: "Dermatology", vitals: { bp: "115/70", hr: 68 } } },
    { patientId: "P-1102", author: "Dr. Rohan Chawla", data: { diagnosis: "Androgenetic Alopecia - Male Pattern (Norwood IV)", notes: "32-year-old with progressive frontoparietal hair loss for 5 years. Dermoscopy: hair diameter diversity, peripilar signs. Started on Finasteride 1mg daily + Minoxidil 5% topical. Platelet-rich plasma therapy discussed. Realistic expectations counseling provided.", department: "Dermatology", vitals: { bp: "120/76", hr: 70 } } },
    { patientId: "P-1103", author: "Dr. Tanya Kapoor", data: { diagnosis: "Vitiligo - Segmental", notes: "22-year-old with depigmented patch on right hand and wrist for 6 months. Wood's lamp confirms vitiligo. Segmental distribution. Started on topical Tacrolimus 0.1% for facial areas, potent topical steroid for body. Narrow-band UVB phototherapy initiated. Early treatment critical.", department: "Dermatology", vitals: { bp: "118/72", hr: 68 } } },
    { patientId: "P-1104", author: "Dr. Rohan Chawla", data: { diagnosis: "Photoaging & Solar Lentigines", notes: "55-year-old with multiple solar lentigines on face and dorsum of hands. Skin type III. History of chronic sun exposure. Q-switched Nd:YAG laser performed for lentigines. Tretinoin 0.025% cream for general photoaging. Strict sun protection reinforced.", department: "Dermatology", vitals: { bp: "122/74", hr: 72 } } },
    { patientId: "P-1105", author: "Dr. Tanya Kapoor", data: { diagnosis: "Seborrheic Dermatitis", notes: "40-year-old with recurrent erythematous, scaly patches on nasolabial folds, eyebrows, and scalp. Flares with stress and cold weather. Ketoconazole 2% cream for face, zinc pyrithione shampoo for scalp. Low-potency topical steroid for flares. Maintenance with moisturizers.", department: "Dermatology", vitals: { bp: "120/76", hr: 68 } } },
    { patientId: "P-1106", author: "Dr. Rohan Chawla", data: { diagnosis: "Chemical Peel - Melasma", notes: "35-year-old with bilateral malar hyperpigmentation (melasma). Fitzpatrick skin type IV. Previous treatment with hydroquinone partial response. Glycolic acid peel 35% performed. Sunscreen SPF 50 mandatory. Tri-Luma cream for maintenance. Series of 6 peels planned.", department: "Dermatology", vitals: { bp: "115/70", hr: 66 } } },
    { patientId: "P-1107", author: "Dr. Tanya Kapoor", data: { diagnosis: "Urticaria - Chronic Spontaneous", notes: "28-year-old with recurrent wheals and angioedema for >6 weeks. No identifiable trigger. Total IgE elevated. C4 low. Started on second-generation antihistamine (Cetirizine 10mg) doubled dose. Omalizumab considered if not controlled. Dermatographism positive.", department: "Dermatology", vitals: { bp: "118/72", hr: 72 } } },
    { patientId: "P-1108", author: "Dr. Rohan Chawla", data: { diagnosis: "Botulinum Toxin - Cosmetic", notes: "45-year-old female for cosmetic rejuvenation. Forehead lines, glabellar lines, and crow's feet. OnabotulinumtoxinA: 20 units glabella, 12 units forehead, 24 units crow's feet. Procedure well-tolerated. Results in 3-7 days, lasting 3-4 months. Avoid lying flat for 4 hours.", department: "Dermatology", vitals: { bp: "118/72", hr: 68 } } }
  ],
  "Radiology & Diagnostics": [
    { patientId: "P-1109", author: "Dr. Deepa Natarajan", data: { diagnosis: "MRI Brain - Normal Study", notes: "52-year-old with chronic headaches. MRI brain with and without contrast: normal gray-white matter differentiation. No mass lesion, no midline shift, no abnormal enhancement. Ventricles normal in size and configuration. No restricted diffusion. Impression: Normal MRI brain.", department: "Radiology", modality: "MRI", body_part: "Brain" } },
    { patientId: "P-1110", author: "Dr. Kunal Singhania", data: { diagnosis: "CT Chest - Pulmonary Embolism", notes: "45-year-old with acute onset dyspnea and pleuritic chest pain. CT pulmonary angiography: bilateral segmental pulmonary emboli in lower lobes. No evidence of right heart strain. No consolidation or effusion. Impression: Acute bilateral PE. Anticoagulation initiated.", department: "Radiology", modality: "CT", body_part: "Chest" } },
    { patientId: "P-1111", author: "Dr. Deepa Natarajan", data: { diagnosis: "Mammography - BI-RADS 4B", notes: "55-year-old routine screening. Right breast: irregular spiculated mass at 2 o'clock, 1.5cm. Microcalcifications present. BI-RADS 4B (moderate suspicion). Ultrasound-guided core biopsy recommended. Left breast: BI-RADS 1 (normal). Dense breast tissue noted.", department: "Radiology", modality: "Mammography", body_part: "Bilateral Breasts" } },
    { patientId: "P-1112", author: "Dr. Kunal Singhania", data: { diagnosis: "Ultrasound Abdomen - Cholelithiasis", notes: "38-year-old with right upper quadrant pain. Ultrasound abdomen: multiple gallbladder stones, largest 1.8cm. No gallbladder wall thickening, no pericholecystic fluid. Common bile duct normal diameter (5mm). Liver parenchyma normal. Kidneys normal bilaterally.", department: "Radiology", modality: "Ultrasound", body_part: "Abdomen" } },
    { patientId: "P-1113", author: "Dr. Deepa Natarajan", data: { diagnosis: "CT Abdomen - Appendicitis", notes: "22-year-old with right iliac fossa pain. CT abdomen with contrast: appendix 14mm diameter, appendicolith present, periappendiceal fat stranding. No perforation or abscess. Diagnosis: Acute uncomplicated appendicitis. Surgical consultation obtained.", department: "Radiology", modality: "CT", body_part: "Abdomen & Pelvis" } },
    { patientId: "P-1114", author: "Dr. Kunal Singhania", data: { diagnosis: "X-Ray Chest - Pneumonia", notes: "65-year-old with fever and cough. Chest X-ray PA view: right lower lobe consolidation with air bronchograms. No pleural effusion. Heart size normal. No mediastinal widening. Impression: Right lower lobe pneumonia. Clinical correlation recommended.", department: "Radiology", modality: "X-Ray", body_part: "Chest" } },
    { patientId: "P-1115", author: "Dr. Deepa Natarajan", data: { diagnosis: "MRI Spine - Lumbar Disc Herniation", notes: "48-year-old with radicular pain in left leg. MRI lumbar spine: L4/L5 broad-based disc herniation with left foraminal extension. Left L4 nerve root compression. Mild spinal stenosis. No cauda equina compression. Impression: L4/L5 disc herniation with left foraminal stenosis.", department: "Radiology", modality: "MRI", body_part: "Lumbar Spine" } },
    { patientId: "P-1116", author: "Dr. Kunal Singhania", data: { diagnosis: "CT Head - Acute Hemorrhage", notes: "78-year-old sudden severe headache. CT head without contrast: right basal ganglia intracerebral hemorrhage, approximately 25mL. Mild midline shift (3mm). No intraventricular extension. No hydrocephalus. Impression: Acute right basal ganglia ICH. Neurosurgical consultation.", department: "Radiology", modality: "CT", body_part: "Head" } },
    { patientId: "P-1117", author: "Dr. Deepa Natarajan", data: { diagnosis: "DEXA Scan - Osteoporosis", notes: "65-year-old female post-menopausal. DXA scan: Lumbar spine T-score -3.2, femoral neck T-score -2.8. Diagnosis: Osteoporosis. Fragility fracture risk: high. Initiated on Denosumab 60mg SC every 6 months. Calcium and Vitamin D supplementation. Fall prevention counseling.", department: "Radiology", modality: "DEXA", body_part: "Lumbar Spine & Femoral Neck" } },
    { patientId: "P-1118", author: "Dr. Kunal Singhania", data: { diagnosis: "CT Pulmonary Angiography - Normal", notes: "42-year-old with pleuritic chest pain and elevated D-dimer. CT pulmonary angiography: no filling defects in main, lobar, or segmental pulmonary arteries. No alternative diagnosis. Heart size normal. No pericardial effusion. Impression: Negative for pulmonary embolism.", department: "Radiology", modality: "CT", body_part: "Chest (CTPA)" } },
    { patientId: "P-1119", author: "Dr. Deepa Natarajan", data: { diagnosis: "Ultrasound Obstetrics - Normal Growth Scan", notes: "30-year-old G1P0 at 32 weeks. Obstetric ultrasound: single live fetus, cephalic presentation. BPD: 80mm (32w2d), HC: 295mm (32w1d), AC: 280mm (32w3d), FL: 62mm (32w0d). EFW: 1850g (50th percentile). AFI: 14cm (normal). Placenta: anterior, Grade 1. Cord: 3 vessels.", department: "Radiology", modality: "Ultrasound", body_part: "Obstetric" } },
    { patientId: "P-1120", author: "Dr. Kunal Singhania", data: { diagnosis: "PET-CT - Lymphoma Staging", notes: "38-year-old with newly diagnosed Hodgkin lymphoma. PET-CT: FDG-avid lymphadenopathy in cervical, mediastinal, and para-aortic regions. Spleen shows patchy uptake. No extranodal disease. Lugano classification: Stage III. Interim PET after 2 cycles of ABVD planned.", department: "Radiology", modality: "PET-CT", body_part: "Whole Body" } }
  ],
  "Emergency & Critical Care": [
    { patientId: "P-1121", author: "Dr. Manish Tandon", data: { diagnosis: "Polytrauma - Road Traffic Accident", notes: "28-year-old male brought by EMS after motorcycle accident. GCS 14 (E4V4M6). Multiple abrasions left side. Chest X-ray: left rib fractures (5-8), small hemothorax. CT: grade II splenic laceration. Managed non-operatively. Chest tube for hemothorax. Serial abdominal exams.", department: "Emergency", vitals: { bp: "110/70", hr: 115, spo2: "93%", gcs: 14 } } },
    { patientId: "P-1122", author: "Dr. Sneha Patil", data: { diagnosis: "Anaphylaxis", notes: "25-year-old with acute onset urticaria, angioedema, and wheezing after bee sting. BP 78/50, HR 130. Immediate IM Epinephrine 0.5mg administered. IV normal saline bolus. Secondary: Hydrocortisone 200mg IV + Diphenhydramine 50mg IV. Response within 10 minutes. Observed for biphasic reaction.", department: "Emergency", vitals: { bp: "78/50", hr: 130, spo2: "91%" } } },
    { patientId: "P-1123", author: "Dr. Manish Tandon", data: { diagnosis: "Acute Myocardial Infarction - STEMI", notes: "58-year-old male with crushing substernal chest pain radiating to left arm. ECG: ST elevation II, III, aVF. STEMI alert activated. Clopidogrel 300mg loading dose. Aspirin 325mg. Heparin bolus. Emergency cath lab: PCI with drug-eluting stent to RCA. Door-to-balloon time: 52 minutes.", department: "Emergency", vitals: { bp: "95/60", hr: 108, spo2: "94%" } } },
    { patientId: "P-1124", author: "Dr. Sneha Patil", data: { diagnosis: "Diabetic Ketoacidosis", notes: "22-year-old Type 1 DM with 2-day nausea, vomiting, and abdominal pain. Blood glucose 580 mg/dL, pH 7.12, bicarb 8, ketones large. Started on IV insulin infusion (0.1 units/kg/hr). Aggressive IV fluid resuscitation (NS). Potassium monitoring q2h. DKA resolved in 18 hours.", department: "Emergency", vitals: { bp: "105/65", hr: 120, spo2: "97%", glucose: "580mg/dL" } } },
    { patientId: "P-1125", author: "Dr. Manish Tandon", data: { diagnosis: "Acute Asthma Exacerbation - Severe", notes: "30-year-old with acute wheeze and respiratory distress. PEF 150 L/min (personal best 450). SpO2 88% on room air. Triple therapy: Nebulized Salbutamol + Ipratropium q20min x 3, IV Hydrocortisone 200mg. BiPAP initiated. Improved to PEF 300 after 2 hours. Admitted for observation.", department: "Emergency", vitals: { bp: "135/85", hr: 118, spo2: "88%" } } },
    { patientId: "P-1126", author: "Dr. Sneha Patil", data: { diagnosis: "Subarachnoid Hemorrhage", notes: "48-year-old with thunderclap headache, worst of life. CT head: diffuse SAH in basal cisterns (Fisher grade 3). BP managed to <160/100. Nimodipine 60mg q4h started. Neurosurgical consultation: CTA to identify aneurysm. ICU admission for close monitoring.", department: "Critical Care", vitals: { bp: "178/105", hr: 92, spo2: "96%", gcs: 14 } } },
    { patientId: "P-1127", author: "Dr. Manish Tandon", data: { diagnosis: "Severe Sepsis - Pneumonia", notes: "72-year-old with fever, hypotension, and altered sensorium. Lactate 4.5. Blood pressure 82/50 on fluids. Started on Norepinephrine infusion. Broad-spectrum antibiotics: Piperacillin-Tazobactam. Central line and arterial line placed. Admitted to ICU. Source: chest X-ray shows bilateral infiltrates.", department: "Critical Care", vitals: { temp: "39.8°C", bp: "82/50", hr: 125, spo2: "88%", lactate: "4.5" } } },
    { patientId: "P-1128", author: "Dr. Sneha Patil", data: { diagnosis: "Cardiac Arrest - ROSC Achieved", notes: "65-year-old found unresponsive. Bystander CPR initiated. EMS arrival: VF rhythm, defibrillated x 3. ROSC achieved after 18 minutes. Post-arrest care: targeted temperature management (33°C). ECG: STEMI. Emergent cath lab: LAD stent. ICU admission for neuroprognostication.", department: "Critical Care", vitals: { bp: "90/55", hr: 110, spo2: "94%", temp: "33°C" } } },
    { patientId: "P-1129", author: "Dr. Manish Tandon", data: { diagnosis: "Status Epilepticus", notes: "35-year-old with ongoing generalized tonic-clonic seizure for >5 minutes on arrival. Lorazepam 4mg IV administered, seizure stopped. Recurrent at 10 minutes: additional 4mg. Levetiracetam 3000mg IV loaded. CT head: normal. EEG: generalized periodic discharges. ICU admission for monitoring.", department: "Emergency", vitals: { bp: "165/95", hr: 135, spo2: "91%", gcs: 6 } } },
    { patientId: "P-1130", author: "Dr. Sneha Patil", data: { diagnosis: "Intoxications - Methanol", notes: "28-year-old with visual disturbances and metabolic acidosis after ingestion of home-brewed alcohol. pH 7.1, anion gap 28. Osmolar gap elevated. Serum methanol level: 45 mg/dL. Started on Fomepizole 15mg/kg loading. Hemodialysis initiated. Visual symptoms improving.", department: "Critical Care", vitals: { bp: "110/70", hr: 105, spo2: "95%", ph: "7.1" } } },
    { patientId: "P-1131", author: "Dr. Manish Tandon", data: { diagnosis: "Traumatic Brain Injury - Severe", notes: "20-year-old assault victim. GCS 7 (E1V2M4). CT head: right acute subdural hematoma with 8mm midline shift. Emergency craniotomy and hematoma evacuation. ICP monitor placed. Post-op ICU: ICP monitoring, serial CT heads. Mannitol and hyperventilation for ICP spikes.", department: "Critical Care", vitals: { bp: "145/90", hr: 100, spo2: "93%", gcs: 7, icp: "22mmHg" } } },
    { patientId: "P-1132", author: "Dr. Sneha Patil", data: { diagnosis: "Tension Pneumothorax", notes: "32-year-old stabbing wound left chest. Hypotension, JVD, tracheal deviation to right. Absent breath sounds left side. Immediate needle decompression (2nd ICS MCL) followed by chest tube insertion. 800mL hemothorax evacuated. Hemodynamic stability restored. Admitted for observation.", department: "Emergency", vitals: { bp: "80/50", hr: 130, spo2: "88%" } } }
  ]
};

console.log("=== HealthLedger Sample Data Generator ===\n");
console.log("Creating sample records for all departments...\n");

let totalRecords = 0;
for (const [department, records] of Object.entries(sampleRecords)) {
  console.log(`\n📁 ${department} (${records.length} records):`);
  for (const record of records) {
    try {
      ledger.addTransaction({
        patientId: record.patientId,
        author: record.author,
        data: record.data
      });
      console.log(`  ✓ ${record.patientId} - ${record.data.diagnosis} (by ${record.author})`);
      totalRecords++;
    } catch (error) {
      console.log(`  ✗ ${record.patientId} - Error: ${error.message}`);
    }
  }
}

console.log(`\n\n=== Summary ===`);
console.log(`Total records created: ${totalRecords}`);
console.log(`Departments covered: ${Object.keys(sampleRecords).length}`);
console.log(`\nTo add these records to your blockchain, run the API server and submit records via POST /api/records`);
console.log(`\nAlternatively, you can mine these transactions into the blockchain.`);
